export const products = {
  featuredGrocery: {
    id: "ccc1",
    category: { en: "Featured Grocery", ar: "مواد غذائية مميزة" },
    products: [
      {
        id: "p1",
        name: { en: "Revana Tomato Sauce 800gm", ar: "صلصة طماطم ريفانا 800جرام" },
        price: {
          beforeDiscount: 150,
          discountPercentage: 0,
          discount: 0,
          afterDiscount: 150,
        },
        rating: 4,
        image: "/images/products/p1.png",
      },
      {
        id: "p2",
        name: { en: "Revana Tomato Sauce 800gm", ar: "صلصة طماطم ريفانا 800جرام" },
        price: {
          beforeDiscount: 200,
          discountPercentage: 0,
          discount: 0,
          afterDiscount: 200,
        },
        rating: 4,
        image: "/images/products/p2.png",
      },
      {
        id: "p3",
        name: { en: "Revana Tomato Sauce 800gm", ar: "صلصة طماطم ريفانا 800جرام" },
        price: {
          beforeDiscount: 180,
          discountPercentage: 0,
          discount: 0,
          afterDiscount: 180,
        },
        rating: 4,
        image: "/images/products/p3.png",
      },
      {
        id: "p4",
        name: { en: "Revana Tomato Sauce 800gm", ar: "صلصة طماطم ريفانا 800جرام" },
        price: {
          beforeDiscount: 240,
          discountPercentage: 0,
          discount: 0,
          afterDiscount: 240,
        },
        rating: 4,
        image: "/images/products/p4.png",
      },
      {
        id: "p5",
        name: { en: "Revana Tomato Sauce 800gm", ar: "صلصة طماطم ريفانا 800جرام" },
        price: {
          beforeDiscount: 230,
          discountPercentage: 0,
          discount: 0,
          afterDiscount: 230,
        },
        rating: 4,
        image: "/images/products/p5.png",
      },
      {
        id: "p6",
        name: { en: "Revana Tomato Sauce 800gm", ar: "صلصة طماطم ريفانا 800جرام" },
        price: {
          beforeDiscount: 190,
          discountPercentage: 0,
          discount: 0,
          afterDiscount: 190,
        },
        rating: 4,
        image: "/images/products/p6.png",
      },
      {
        id: "p7",
        name: { en: "Revana Tomato Sauce 800gm", ar: "صلصة طماطم ريفانا 800جرام" },
        price: {
          beforeDiscount: 190,
          discountPercentage: 0,
          discount: 0,
          afterDiscount: 190,
        },
        rating: 4,
        image: "/images/products/p1.png",
      },
      {
        id: "p8",
        name: { en: "Revana Tomato Sauce 800gm", ar: "صلصة طماطم ريفانا 800جرام" },
        price: {
          beforeDiscount: 190,
          discountPercentage: 0,
          discount: 0,
          afterDiscount: 190,
        },
        rating: 4,
        image: "/images/products/p2.png",
      },
    ],
  },
  beautyPicks: {
    id: "ccc2",
    category: { en: "Beauty Picks", ar: "مختارات الجمال" },
    products: [
      {
        id: "p1",
        name: { en: "Revana Tomato Sauce 800gm", ar: "صلصة طماطم ريفانا 800جرام" },
        price: {
          beforeDiscount: 150,
          discountPercentage: 0,
          discount: 0,
          afterDiscount: 150,
        },
        rating: 4,
        image: "/images/products/p1.png",
      },
      {
        id: "p2",
        name: { en: "Revana Tomato Sauce 800gm", ar: "صلصة طماطم ريفانا 800جرام" },
        price: {
          beforeDiscount: 200,
          discountPercentage: 0,
          discount: 0,
          afterDiscount: 200,
        },
        rating: 4,
        image: "/images/products/p2.png",
      },
      {
        id: "p3",
        name: { en: "Revana Tomato Sauce 800gm", ar: "صلصة طماطم ريفانا 800جرام" },
        price: {
          beforeDiscount: 180,
          discountPercentage: 0,
          discount: 0,
          afterDiscount: 180,
        },
        rating: 4,
        image: "/images/products/p3.png",
      },
      {
        id: "p4",
        name: { en: "Revana Tomato Sauce 800gm", ar: "صلصة طماطم ريفانا 800جرام" },
        price: {
          beforeDiscount: 240,
          discountPercentage: 0,
          discount: 0,
          afterDiscount: 240,
        },
        rating: 4,
        image: "/images/products/p4.png",
      },
      {
        id: "p5",
        name: { en: "Revana Tomato Sauce 800gm", ar: "صلصة طماطم ريفانا 800جرام" },
        price: {
          beforeDiscount: 230,
          discountPercentage: 0,
          discount: 0,
          afterDiscount: 230,
        },
        rating: 4,
        image: "/images/products/p5.png",
      },
      {
        id: "p6",
        name: { en: "Revana Tomato Sauce 800gm", ar: "صلصة طماطم ريفانا 800جرام" },
        price: {
          beforeDiscount: 190,
          discountPercentage: 0,
          discount: 0,
          afterDiscount: 190,
        },
        rating: 4,
        image: "/images/products/p6.png",
      },
    ],
  },
  featuredGroceryProducts: {
    id: "ccc3",
    category: { en: "Featured Grocery Products", ar: "مواد بقالة مميزة" },
    products: [
      {
        id: "p1",
        name: { en: "Revana Tomato Sauce 800gm", ar: "صلصة طماطم ريفانا 800جرام" },
        price: {
          beforeDiscount: 150,
          discountPercentage: 0,
          discount: 0,
          afterDiscount: 150,
        },
        rating: 4,
        image: "/images/products/p1.png",
      },
      {
        id: "p2",
        name: { en: "Revana Tomato Sauce 800gm", ar: "صلصة طماطم ريفانا 800جرام" },
        price: {
          beforeDiscount: 200,
          discountPercentage: 0,
          discount: 0,
          afterDiscount: 200,
        },
        rating: 4,
        image: "/images/products/p2.png",
      },
      {
        id: "p3",
        name: { en: "Revana Tomato Sauce 800gm", ar: "صلصة طماطم ريفانا 800جرام" },
        price: {
          beforeDiscount: 180,
          discountPercentage: 0,
          discount: 0,
          afterDiscount: 180,
        },
        rating: 4,
        image: "/images/products/p3.png",
      },
      {
        id: "p4",
        name: { en: "Revana Tomato Sauce 800gm", ar: "صلصة طماطم ريفانا 800جرام" },
        price: {
          beforeDiscount: 240,
          discountPercentage: 0,
          discount: 0,
          afterDiscount: 240,
        },
        rating: 4,
        image: "/images/products/p4.png",
      },
      {
        id: "p5",
        name: { en: "Revana Tomato Sauce 800gm", ar: "صلصة طماطم ريفانا 800جرام" },
        price: {
          beforeDiscount: 230,
          discountPercentage: 0,
          discount: 0,
          afterDiscount: 230,
        },
        rating: 4,
        image: "/images/products/p5.png",
      },
      {
        id: "p6",
        name: { en: "Revana Tomato Sauce 800gm", ar: "صلصة طماطم ريفانا 800جرام" },
        price: {
          beforeDiscount: 190,
          discountPercentage: 0,
          discount: 0,
          afterDiscount: 190,
        },
        rating: 4,
        image: "/images/products/p6.png",
      },
    ],
  },
};
